GET http://localhost:7160/api/messages
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU

# Example 200 response
# {
#   "data": [
#     {
#       "sending_user_id": 502, //FIXME
#       "receiving_user_id": 6,
#       "content": "hey man",
#       "created_at": "2021-11-08T15:56:00.000Z"
#     },
#     {
#       "sending_user_id": 6,
#       "receiving_user_id": 502,
#       "content": "sup dude",
#       "created_at": "2021-11-08T15:56:35.000Z"
#     }
#   ]
# }

##############################################################

POST http://localhost:7160/api/messages
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU
Content-Type: application/json

{
    "receiverId": "6bb5a01f-4e56-4307-87f4-ca51dd40dd57",
    "content" : "hey man"
}

# Example 200 response:
# {
#     "data": "Message sent"
# }