GET http://localhost:7160/messages
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8 //FIXME

# Example 200 response
# {
#   "data": [
#     {
#       "sending_user_id": 502, //FIXME
#       "receiving_user_id": 6,
#       "content": "hey man",
#       "created_at": "2021-11-08T15:56:00.000Z"
#     },
#     {
#       "sending_user_id": 6,
#       "receiving_user_id": 502,
#       "content": "sup dude",
#       "created_at": "2021-11-08T15:56:35.000Z"
#     }
#   ]
# }

##############################################################

POST http://localhost:7160/messages
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8 //FIXME
Content-Type: application/json

{
    "receiverId": 6, //FIXME
    "content" : "hey man"
}

# Example 200 response:
# {
#     "data": "Message sent"
# }