GET http://localhost:7160/messages
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8

# Example response:
# {
#   "data": [
#     {
#       "content": "1v1 me noob",
#       "sentAt": 1636192643573
#     }
#   ]
# }

###

// neo4j id example = 5
// mysql id example = 7
// mongo id example = 617ab04a92095632d0aec9dc
POST http://localhost:7160/messages
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
Content-Type: application/json

{
    "receiverId": 6,
    "content" : "hey man"
}

# Example response:
# {
#     "data": "Message sent"
# }