GET http://localhost:7160/api/swipes/matches
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU

# Example 200 response:
# {
#   "data": [
#     {
#       "username": "Madeson Bell",
#       "bio": "molestie. Sed id risus quis",
#       "games": [
#         {
#           "id": 5,
#           "name": "Rocket Leauge",
#           "rank": "sit",
#           "genre": "Sport",
#           "comment": "convallis convallis dolor.",
#           "publisher": "Psynoix"
#         }
#       ],
#       "platforms": [
#         {
#           "id": 4,
#           "gamertag": "Haley",
#           "platform": "Origin"
#         }
#       ]
#     }
#   ]
# }

# 404 response:
# {
#   "data": "Did not find any matches"
# }

##############################################################

POST http://localhost:7160/api/swipes/swipe
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU
Content-Type: application/json

{
    "otherUserId": "5017e1c1-5b07-46f5-934a-ebe541b7588a"
}

# Example response:
# {
#   "data": "Swiped on user"
# }