GET http://localhost:7160/swipes/matches
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8 //FIXME

# Example 200 response:
# {
#   "data": [
#     {
#       "username": "Madeson Bell",
#       "bio": "molestie. Sed id risus quis",
#       "games": [
#         {
#           "id": 5,
#           "name": "Rocket Leauge",
#           "rank": "sit",
#           "genre": "Sport",
#           "comment": "convallis convallis dolor.",
#           "publisher": "Psynoix"
#         }
#       ],
#       "platforms": [
#         {
#           "id": 4,
#           "gamertag": "Haley",
#           "platform": "Origin"
#         }
#       ]
#     }
#   ]
# }

# 404 response:
# {
#   "data": "Did not find any matches"
# }

##############################################################

POST http://localhost:7160/swipes/swipe
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8 //FIXME
Content-Type: application/json

{
    "otherUserId": 6 //FIXME
}

# Example response:
# {
#   "data": "Swiped on user"
# }