GET http://localhost:7160/swipes/matches
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8

# Example response:
# {
#   "data": [
#     {
#       "bio": "chinsUnite",
#       "username": "BigChinny"
#     }
#   ]
# }

###

// neo4j id example = // FIXME
// mysql id example = // FIXME
// mongo id example = // FIXME
POST http://localhost:7160/swipes/swipeonuser
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
Content-Type: application/json

{
    "otherUserId": 6
}

# Example response:
# {
#   "data": "Swiped on user"
#   ]
# }