GET http://localhost:7160/users
# neo4j token
#authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
# mysql token
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8

// FIXME neo4j needs games+platforms

# Example 200 response:
# {
#   "data": [
#     {
#       "bio": "rhoncus. Nullam velit dui, semper et,",
#       "username": "Libby Sherman",
#       "games": [
#         {
#           "id": 2,
#           "name": "CS:GO",
#           "rank": "das",
#           "genre": "Shooter",
#           "comment": "fasdfasdfas",
#           "publisher": "Valve"
#         },
#         {
#           "id": 5,
#           "name": "Rocket Leauge",
#           "rank": "eget",
#           "genre": "Sport",
#           "comment": "id, blandit at,",
#           "publisher": "Psynoix"
#         }
#       ],
#       "platforms": [
#         {
#           "id": 2,
#           "gamertag": "Shana",
#           "platform": "Riot"
#         }
#       ]
#     },
# etc...
 
# Example 404 response:
# {
#   "data": "Could not find user"
# }

##############################################################

// neo4j id example = 5
// mysql id example = 7
// mongo id example = 617ab04a92095632d0aec9dc
GET http://localhost:7160/users/7
# neo4j token
#authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
# mysql token
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8


# Example 200 response:
# {
#   "data": {
#     "bio": "tincidunt orci quis lectus. Nullam suscipit,",
#     "username": "Hyatt Campos",
#     "games": [
#       {
#         "id": 10,
#         "name": "Minecraft",
#         "rank": "eget",
#         "genre": "Adventure",
#         "comment": "Mauris vel turpis.",
#         "publisher": "Mojang"
#       }
#     ],
#     "platforms": [
#       {
#         "id": 4,
#         "gamertag": "Mara",
#         "platform": "Origin"
#       }
#     ]
#   }
# }

# Example 404 response:
# {
#   "data": "Could not find user"
# }

##############################################################

POST http://localhost:7160/users/signin
Content-Type: application/json

{
	"email": "mysql0@example.com",
	"password": "1234"
}

# Example 200 response:
# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MjIxNTU2fQ.p-c3fElNp46cl-HLsD7B8Ny_jj0p1dUEpea-yTQlm8M",
#   "user": {
#     "bio": "wowow",
#     "email": "wowow@big.dk",
#     "username": "Wowzas"
#   }
# }

# Example 404 response:
# {
#   "data": "Could not find user"
# }

##############################################################

POST http://localhost:7160/users/signup
Content-Type: application/json

{
	"username": "mysql_example0",
	"email": "mysql0@example.com",
	"password": "1234",
	"bio": "just an example"
}

# 200 response:
# {
#   "data": "Your account has been created"
# }

# 400 response:
# {
#   "data": "User with that email or username already exists"
# }


# 400 response:
# {
#   "data": "Please fill all fields"
# }

##############################################################

PUT http://localhost:7160/users/addplatformtouser
# neo4j token
#authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
# mysql token
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8

Content-Type: application/json


# FIXME neo4j + mongo use id for platforms instead of name
# means that mongo should not store entire platform in object, but only id

{
	"platform" : {
		"platformId": 5, //FIXME relevant id
		"gamertag": "muchsteam"
	}
}

# 200 response:
# {
#   "data": "Platform added"
# }

##############################################################

PUT http://localhost:7160/users/addgametouser
# neo4j token
#authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
# mysql token
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTAyLCJpYXQiOjE2MzYzNzczOTh9.qUbrMyg6XZCqct5HicFmBBoneNJyjEMT7McOmV3Tc-8
Content-Type: application/json

# FIXME neo4j + mongo use id for games instead of name
# means that mongo should not store entire game in object, but only id
//FIXME relevant game + platform id
{
	"game" : {
		"gameId": 4, 
		"platformId": 5,
		"rank": 50,
		"comment": ""
	}
}

# 200 response:
# {
#   "data": "Games added"
# }