GET http://localhost:7160/api/users
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU

# Example 200 response:
# {
#   "data": [
#     {
#       "bio": "rhoncus. Nullam velit dui, semper et,",
#       "username": "Libby Sherman",
#       "games": [
#         {
#           "id": 2,
#           "name": "CS:GO",
#           "rank": "das",
#           "genre": "Shooter",
#           "comment": "fasdfasdfas",
#           "publisher": "Valve"
#         },
#         {
#           "id": 5,
#           "name": "Rocket Leauge",
#           "rank": "eget",
#           "genre": "Sport",
#           "comment": "id, blandit at,",
#           "publisher": "Psynoix"
#         }
#       ],
#       "platforms": [
#         {
#           "id": 2,
#           "gamertag": "Shana",
#           "platform": "Riot"
#         }
#       ]
#     },
# etc...
 
# 404 response:
# {
#   "data": "Could not find user"
# }

##############################################################

GET http://localhost:7160/api/users/6bb5a01f-4e56-4307-87f4-ca51dd40dd57
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU

# Example 200 response:
# {
#   "data": {
#     "bio": "tincidunt orci quis lectus. Nullam suscipit,",
#     "username": "Hyatt Campos",
#     "games": [
#       {
#         "id": 10,
#         "name": "Minecraft",
#         "rank": "eget",
#         "genre": "Adventure",
#         "comment": "Mauris vel turpis.",
#         "publisher": "Mojang"
#       }
#     ],
#     "platforms": [
#       {
#         "id": 4,
#         "gamertag": "Mara",
#         "platform": "Origin"
#       }
#     ]
#   }
# }

# 404 response:
# {
#   "data": "Could not find user"
# }

##############################################################

POST http://localhost:7160/api/users/signin
Content-Type: application/json

{
	"email": "mysql1@example.com",
	"password": "1234"
}

# Example 200 response:
# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MjIxNTU2fQ.p-c3fElNp46cl-HLsD7B8Ny_jj0p1dUEpea-yTQlm8M",
#   "user": {
#    "id": "9c2d40e1-c256-4033-b565-5500c98ce80d",
#    "username": "mysql_example1",
#    "email": "mysql1@example.com",
#    "bio": "just an example"
#  }
# }

# 404 response:
# {
#   "data": "Could not find user"
# }

##############################################################

POST http://localhost:7160/api/users/signup
Content-Type: application/json

{
	"username": "mysql_example4",
	"email": "mysql4@example.com",
	"password": "1234",
	"bio": "just an example"
}

# 200 response:
# {
#   "data": "Your account has been created"
# }

# 400 response:
# {
#   "data": "User with that email or username already exists"
# }

# 400 response:
# {
#   "data": "Please fill all fields"
# }

##############################################################

PUT http://localhost:7160/api/users/addplatformtouser
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU
Content-Type: application/json

{
	"platform" : {
		"platformId": 1,
		"gamertag": "muchsteam"
	}
}

# 200 response:
# {
#   "data": "Platform added"
# }

##############################################################

PUT http://localhost:7160/api/users/addgametouser
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljMmQ0MGUxLWMyNTYtNDAzMy1iNTY1LTU1MDBjOThjZTgwZCIsImlhdCI6MTYzODcwMjk3Nn0.VmIXxI3xm2rF4RtXESTbmbvWscKHHu83Ypm-PUsJoXU
Content-Type: application/json

{
	"game" : {
		"gameId": 7, 
		"platformId": 1,
		"rank": "50",
		"comment": ""
	}
}

# 200 response:
# {
#   "data": "Games added"
# }