GET http://localhost:7160/users
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8

# Example response:
# {
#   "data": [
#     {
#       "bio": "chinsUnite",
#       "username": "BigChinny"
#     },
#     {
#       "bio": "bobbylobby",
#       "username": "Bobby"
#     }
#   ]
# }

###

// neo4j id example = 5
// mysql id example = // FIXME
// mongo id example = // FIXME
GET http://localhost:7160/users/5
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8

# Example response:
# {
#   "data": {
#     "bio": "wowow",
#     "email": "wowow@big.dk",
#     "username": "Wowzas"
#   }
# }

###

POST http://localhost:7160/users/signin
Content-Type: application/json

{
	"email": "wowow@big.dk",
	"password": "1234"
}

# Example response:
# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MjIxNTU2fQ.p-c3fElNp46cl-HLsD7B8Ny_jj0p1dUEpea-yTQlm8M",
#   "user": {
#     "bio": "wowow",
#     "email": "wowow@big.dk",
#     "username": "Wowzas"
#   }
# }

###

POST http://localhost:7160/users/signup
Content-Type: application/json

{
	"username": "mads",
	"email": "mads@example.com",
	"password": "1234hunter",
	"bio": "g4m3r 4 liiiiiife"
}

# Example response:
# {
#   "data": "Your account has been created"
# }

###

PUT http://localhost:7160/users/addplatformtouser
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
Content-Type: application/json

{
	"platform" : {
		"platformName": "Steam",
		"gamertag": "muchsteam"
	}
}

# Example response:
# {
#   "data": "Platform added"
# }

###

PUT http://localhost:7160/users/addgametouser
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjM2MDQwMTI3fQ.N185EaaL0Q9j4vdr6gss6eQxoUc1cbfVgEtfRrtrNY8
Content-Type: application/json

{
	"game" : {
		"name": "Rocket League",
		"publisher": "Blizzard",
		"genre": "MMORPG",
		"rank": "Gold"
	}
}

# Example response:
# {
#   "data": "Games added"
# }